WITH BASE_ORDERS AS ( SELECT O.CUSTOMER_ID,
                             O.ORDER_ID,
                             O.ORDER_DATE,
                             O.STATUS_CODE,
                             O.TOTAL_AMOUNT,
                             O.CURRENCY_CODE,
                             ROW_NUMBER ()
                                   OVER (PARTITION BY O.CUSTOMER_ID
                                             ORDER BY O.ORDER_DATE DESC, O.ORDER_ID DESC) AS RN
                        FROM ORDER_HEADER O
                       WHERE O.BATCH_ID = 20260520
                         AND O.STATUS_CODE IN ('PAID', 'SHIPPED', 'CLOSED') ),
     CUSTOMER_TOTALS AS ( SELECT B.CUSTOMER_ID,
                                 COUNT (*) AS ORDER_COUNT,
                                 SUM (B.TOTAL_AMOUNT) AS TOTAL_AMOUNT,
                                 MAX (B.ORDER_DATE) AS LAST_ORDER_DATE
                            FROM BASE_ORDERS B
                           WHERE B.RN <= 10
                           GROUP BY B.CUSTOMER_ID )
SELECT C.CUSTOMER_ID,
       C.CUSTOMER_NAME,
       C.EMAIL_ADDRESS,
       CT.ORDER_COUNT,
       CT.TOTAL_AMOUNT,
       CASE
         WHEN CT.TOTAL_AMOUNT >= 10000 THEN 'VIP'
         WHEN CT.TOTAL_AMOUNT >= 5000 THEN 'GOLD'
         WHEN CT.TOTAL_AMOUNT >= 1000 THEN 'SILVER'
         ELSE 'STANDARD'
       END AS CUSTOMER_SEGMENT
  FROM CUSTOMER C
 INNER JOIN CUSTOMER_TOTALS CT ON C.CUSTOMER_ID = CT.CUSTOMER_ID
  LEFT JOIN BASE_ORDERS BO ON C.CUSTOMER_ID = BO.CUSTOMER_ID AND BO.RN = 1
 WHERE C.IS_ACTIVE = 1
   AND (CT.TOTAL_AMOUNT > 0 OR BO.STATUS_CODE = 'PAID')
 ORDER BY CT.TOTAL_AMOUNT DESC,
          C.CUSTOMER_ID ASC
 LIMIT 250
  WITH UR;

 MERGE INTO TGT_CUSTOMER_SUMMARY T
 USING ( SELECT C.CUSTOMER_ID,
                C.CUSTOMER_NAME,
                C.EMAIL_ADDRESS,
                CT.ORDER_COUNT,
                CT.TOTAL_AMOUNT,
                CT.LAST_ORDER_DATE,
                CASE
                  WHEN CT.TOTAL_AMOUNT >= 10000 THEN 'VIP'
                  WHEN CT.TOTAL_AMOUNT >= 5000 THEN 'GOLD'
                  ELSE 'STANDARD'
                END AS SEGMENT_CODE,
                ROW_NUMBER ()
                      OVER (PARTITION BY C.CUSTOMER_ID
                                ORDER BY CT.LAST_ORDER_DATE DESC, C.UPDATED_AT DESC) AS RN
           FROM CUSTOMER C
          INNER JOIN CUSTOMER_TOTALS CT ON C.CUSTOMER_ID = CT.CUSTOMER_ID
          WHERE C.IS_ACTIVE = 1
            AND CT.ORDER_COUNT > 0 ) S ON (T.CUSTOMER_ID = S.CUSTOMER_ID AND S.RN = 1)
  WHEN MATCHED AND ( COALESCE(T.CUSTOMER_NAME, '') <> COALESCE(S.CUSTOMER_NAME, '')
                  OR COALESCE(T.EMAIL_ADDRESS, '') <> COALESCE(S.EMAIL_ADDRESS, '')
                  OR COALESCE(T.SEGMENT_CODE, '') <> COALESCE(S.SEGMENT_CODE, '')
                  OR COALESCE(T.TOTAL_AMOUNT, 0) <> COALESCE(S.TOTAL_AMOUNT, 0) ) THEN
UPDATE
   SET T.CUSTOMER_NAME = S.CUSTOMER_NAME,
       T.EMAIL_ADDRESS = S.EMAIL_ADDRESS,
       T.ORDER_COUNT = S.ORDER_COUNT,
       T.TOTAL_AMOUNT = S.TOTAL_AMOUNT,
       T.LAST_ORDER_DATE = S.LAST_ORDER_DATE,
       T.SEGMENT_CODE = S.SEGMENT_CODE,
       T.UPDATED_AT = CURRENT TIMESTAMP,
       T.UPDATED_BY = CURRENT USER
  WHEN NOT MATCHED THEN
INSERT ( CUSTOMER_ID,
         CUSTOMER_NAME,
         EMAIL_ADDRESS,
         ORDER_COUNT,
         TOTAL_AMOUNT,
         LAST_ORDER_DATE,
         SEGMENT_CODE,
         CREATED_AT,
         CREATED_BY,
         UPDATED_AT,
         UPDATED_BY )
VALUES ( S.CUSTOMER_ID,
         S.CUSTOMER_NAME,
         S.EMAIL_ADDRESS,
         S.ORDER_COUNT,
         S.TOTAL_AMOUNT,
         S.LAST_ORDER_DATE,
         S.SEGMENT_CODE,
         CURRENT TIMESTAMP,
         CURRENT USER,
         CURRENT TIMESTAMP,
         CURRENT USER )
  WITH NC;
