CREATE OR REPLACE PROCEDURE SP_REFRESH_CUSTOMER_STATUS
(
    IN P_CUSTOMER_ID INTEGER
)
LANGUAGE SQL
BEGIN
    UPDATE CUSTOMER
       SET STATUS_CODE = 'ACTIVE',
           UPDATED_AT = CURRENT TIMESTAMP,
           UPDATED_BY = CURRENT USER
     WHERE CUSTOMER_ID = P_CUSTOMER_ID
      WITH NC;
END;
