CREATE OR REPLACE PROCEDURE SP_LOAD_CUSTOMER_SUMMARY
(
    IN P_BATCH_ID INTEGER
)
LANGUAGE SQL
BEGIN
    INSERT INTO CUSTOMER_SUMMARY ( CUSTOMER_ID,
                                   ORDER_COUNT,
                                   TOTAL_AMOUNT,
                                   CREATED_AT,
                                   CREATED_BY )
    SELECT O.CUSTOMER_ID,
           COUNT (*) AS ORDER_COUNT,
           SUM (O.ORDER_TOTAL) AS TOTAL_AMOUNT,
           CURRENT TIMESTAMP AS CREATED_AT,
           CURRENT USER AS CREATED_BY
      FROM ORDER_HEADER O
     WHERE O.BATCH_ID = P_BATCH_ID
       AND O.ORDER_STATUS = 'PAID'
     GROUP BY O.CUSTOMER_ID
    HAVING SUM (O.ORDER_TOTAL) > 0
      WITH NC;

    UPDATE BATCH_CONTROL
       SET FINISHED_AT = CURRENT TIMESTAMP,
           STATUS_CODE = 'DONE'
     WHERE BATCH_ID = P_BATCH_ID
      WITH NC;
END;
