CREATE OR REPLACE FUNCTION FN_CUSTOMER_STATUS
(
    P_CUSTOMER_ID INTEGER
)
RETURNS VARCHAR(20)
LANGUAGE SQL
BEGIN
    RETURN ( SELECT STATUS_CODE
               FROM CUSTOMER
              WHERE CUSTOMER_ID = P_CUSTOMER_ID
              FETCH FIRST 1 ROW ONLY );
END;
