SELECT TRIM (ROUTINE_SCHEMA) AS ROUTINE_SCHEMA,
       TRIM (ROUTINE_NAME) AS ROUTINE_NAME,
       CASE
         WHEN LOCATE ('CB_JAF_P1_TOTAL', UPPER (ROUTINE_DEFINITION)) > 0 THEN 1
         ELSE 0
       END AS USES_JAF_TOTAL,
       CASE
         WHEN LOCATE ('CST_EXT_MSR_MON', UPPER (ROUTINE_DEFINITION)) > 0 THEN 1
         ELSE 0
       END AS USES_CST_EXT,
       CASE
         WHEN LOCATE ('PRC_CST_ADL_PDL4_M_MSR', UPPER (ROUTINE_DEFINITION)) > 0 THEN 1
         ELSE 0
       END AS USES_ADL_PDL4,
       CASE
         WHEN LOCATE ('PRC_CST_PDL4_M_RY_DTL', UPPER (ROUTINE_DEFINITION)) > 0 THEN 1
         ELSE 0
       END AS USES_RY_DTL,
       CASE
         WHEN LOCATE ('-200', UPPER (ROUTINE_DEFINITION)) > 0 THEN 1
         ELSE 0
       END AS USES_ACCOUNT_200,
       CASE
         WHEN LOCATE ('PRC_PD_ID', UPPER (ROUTINE_DEFINITION)) > 0 AND LOCATE ('75', UPPER
           (ROUTINE_DEFINITION)) > 0 THEN 1
         ELSE 0
       END AS POSSIBLE_PD_75_LOGIC
  FROM QSYS2.SYSROUTINES
 WHERE ROUTINE_TYPE = 'PROCEDURE'
   AND ROUTINE_DEFINITION IS NOT NULL
   AND ROUTINE_SCHEMA LIKE 'DW_%'
   AND (LOCATE ('CB_JAF_P1_TOTAL', UPPER (ROUTINE_DEFINITION)) > 0 OR LOCATE ('CST_EXT_MSR_MON', UPPER
       (ROUTINE_DEFINITION)) > 0 OR LOCATE ('PRC_CST_ADL_PDL4_M_MSR', UPPER (ROUTINE_DEFINITION)) > 0 OR LOCATE
       ('PRC_CST_PDL4_M_RY_DTL', UPPER (ROUTINE_DEFINITION)) > 0 OR LOCATE ('-200', UPPER (ROUTINE_DEFINITION)) >
       0)
 ORDER BY ROUTINE_SCHEMA, ROUTINE_NAME
  WITH UR;
