CREATE OR REPLACE PROCEDURE SET_CUSTOMER_STATUS (
P_ID IN NUMBER,
P_STATUS IN VARCHAR2
)
AS
V_UPDATED_AT TIMESTAMP;
BEGIN
UPDATE CUSTOMER SET STATUS = P_STATUS WHERE CUSTOMER_ID = P_ID RETURNING UPDATED_AT INTO V_UPDATED_AT;
DBMS_OUTPUT.PUT_LINE(q'[Updated customer]');
END;
/
