-- DB2 SQL Formatter Example Suite
-- Purpose:
--   A broad beginner-to-advanced DB2 SQL sample file for testing formatter behavior.
--   This is not every DB2 feature, but it intentionally covers many common and advanced patterns. 
-- ============================================================
-- 01. Beginner SELECT statements
-- ============================================================
SELECT 1 FROM SYSIBM.SYSDUMMY1;  SELECT CURRENT DATE AS TODAY, CURRENT TIME AS NOW_TIME, CURRENT TIMESTAMP AS NOW_TS FROM SYSIBM.SYSDUMMY1;  SELECT CUSTOMER_ID, CUSTOMER_NAME, EMAIL_ADDRESS FROM CUSTOMER WHERE IS_ACTIVE = 1 WITH UR;  SELECT CUSTOMER_ID, CUSTOMER_NAME, COALESCE(EMAIL_ADDRESS, 'NO EMAIL') AS EMAIL_ADDRESS, CASE WHEN IS_ACTIVE = 1 THEN 'ACTIVE' ELSE 'INACTIVE' END AS CUSTOMER_STATUS FROM CUSTOMER WHERE CREATED_AT >= DATE('2024-01-01') ORDER BY CUSTOMER_NAME ASC FETCH FIRST 50 ROWS ONLY WITH UR; 
-- ============================================================
-- 02. Filtering, grouping, aggregation
-- ============================================================
SELECT O.CUSTOMER_ID, COUNT(*) AS ORDER_COUNT, SUM(O.TOTAL_AMOUNT) AS TOTAL_AMOUNT, AVG(O.TOTAL_AMOUNT) AS AVG_AMOUNT, MIN(O.ORDER_DATE) AS FIRST_ORDER_DATE, MAX(O.ORDER_DATE) AS LAST_ORDER_DATE FROM ORDER_HEADER O WHERE O.STATUS_CODE IN ('PAID', 'SHIPPED', 'CLOSED') AND O.ORDER_DATE BETWEEN DATE('2024-01-01') AND DATE('2024-12-31') GROUP BY O.CUSTOMER_ID HAVING SUM(O.TOTAL_AMOUNT) >= 1000 ORDER BY TOTAL_AMOUNT DESC WITH UR; 
-- ============================================================
-- 03. Joins
-- ============================================================
SELECT C.CUSTOMER_ID, C.CUSTOMER_NAME, O.ORDER_ID, O.ORDER_DATE, O.TOTAL_AMOUNT, A.CITY, A.COUNTRY_CODE FROM CUSTOMER C INNER JOIN ORDER_HEADER O ON O.CUSTOMER_ID = C.CUSTOMER_ID LEFT JOIN CUSTOMER_ADDRESS A ON A.CUSTOMER_ID = C.CUSTOMER_ID AND A.IS_PRIMARY = 1 WHERE C.IS_ACTIVE = 1 ORDER BY C.CUSTOMER_NAME, O.ORDER_DATE DESC WITH UR; 
-- ============================================================
-- 04. Subqueries
-- ============================================================
SELECT C.CUSTOMER_ID, C.CUSTOMER_NAME, C.EMAIL_ADDRESS FROM CUSTOMER C WHERE EXISTS ( SELECT 1 FROM ORDER_HEADER O WHERE O.CUSTOMER_ID = C.CUSTOMER_ID AND O.STATUS_CODE = 'PAID' ) AND C.CUSTOMER_ID NOT IN ( SELECT B.CUSTOMER_ID FROM CUSTOMER_BLACKLIST B WHERE B.IS_ACTIVE = 1 ) WITH UR;  SELECT O.ORDER_ID, O.CUSTOMER_ID, O.TOTAL_AMOUNT, ( SELECT COUNT(*) FROM ORDER_LINE L WHERE L.ORDER_ID = O.ORDER_ID ) AS LINE_COUNT FROM ORDER_HEADER O WHERE O.ORDER_DATE >= CURRENT DATE - 30 DAYS WITH UR; 
-- ============================================================
-- 05. Common Table Expressions
-- ============================================================
WITH BASE_ORDERS AS ( SELECT O.CUSTOMER_ID, O.ORDER_ID, O.ORDER_DATE, O.STATUS_CODE, O.TOTAL_AMOUNT, ROW_NUMBER() OVER ( PARTITION BY O.CUSTOMER_ID ORDER BY O.ORDER_DATE DESC, O.ORDER_ID DESC ) AS RN FROM ORDER_HEADER O WHERE O.BATCH_ID = 20260520 AND O.STATUS_CODE IN ('PAID', 'SHIPPED', 'CLOSED') ), CUSTOMER_TOTALS AS ( SELECT B.CUSTOMER_ID, COUNT(*) AS ORDER_COUNT, SUM(B.TOTAL_AMOUNT) AS TOTAL_AMOUNT, MAX(B.ORDER_DATE) AS LAST_ORDER_DATE FROM BASE_ORDERS B GROUP BY B.CUSTOMER_ID ) SELECT C.CUSTOMER_ID, C.CUSTOMER_NAME, CT.ORDER_COUNT, CT.TOTAL_AMOUNT, CASE WHEN CT.TOTAL_AMOUNT >= 10000 THEN 'VIP' WHEN CT.TOTAL_AMOUNT >= 5000 THEN 'GOLD' WHEN CT.TOTAL_AMOUNT >= 1000 THEN 'SILVER' ELSE 'STANDARD' END AS CUSTOMER_SEGMENT FROM CUSTOMER C INNER JOIN CUSTOMER_TOTALS CT ON CT.CUSTOMER_ID = C.CUSTOMER_ID LEFT JOIN BASE_ORDERS BO ON BO.CUSTOMER_ID = C.CUSTOMER_ID AND BO.RN = 1 WHERE C.IS_ACTIVE = 1 ORDER BY CT.TOTAL_AMOUNT DESC, C.CUSTOMER_ID ASC FETCH FIRST 250 ROWS ONLY WITH UR; 
-- ============================================================
-- 06. Recursive CTE
-- ============================================================
WITH ORG_TREE (EMPLOYEE_ID, MANAGER_ID, EMPLOYEE_NAME, LEVEL_NO, PATH_TEXT) AS ( SELECT E.EMPLOYEE_ID, E.MANAGER_ID, E.EMPLOYEE_NAME, 1 AS LEVEL_NO, VARCHAR(E.EMPLOYEE_NAME, 1000) AS PATH_TEXT FROM EMPLOYEE E WHERE E.MANAGER_ID IS NULL  UNION ALL  SELECT C.EMPLOYEE_ID, C.MANAGER_ID, C.EMPLOYEE_NAME, P.LEVEL_NO + 1 AS LEVEL_NO, VARCHAR(P.PATH_TEXT || ' > ' || C.EMPLOYEE_NAME, 1000) AS PATH_TEXT FROM EMPLOYEE C INNER JOIN ORG_TREE P ON P.EMPLOYEE_ID = C.MANAGER_ID WHERE P.LEVEL_NO < 10 ) SELECT EMPLOYEE_ID, MANAGER_ID, EMPLOYEE_NAME, LEVEL_NO, PATH_TEXT FROM ORG_TREE ORDER BY PATH_TEXT WITH UR; 
-- ============================================================
-- 07. Window functions
-- ============================================================
SELECT O.CUSTOMER_ID, O.ORDER_ID, O.ORDER_DATE, O.TOTAL_AMOUNT, ROW_NUMBER() OVER ( PARTITION BY O.CUSTOMER_ID ORDER BY O.ORDER_DATE DESC ) AS RN, RANK() OVER ( PARTITION BY O.CUSTOMER_ID ORDER BY O.TOTAL_AMOUNT DESC ) AS AMOUNT_RANK, SUM(O.TOTAL_AMOUNT) OVER ( PARTITION BY O.CUSTOMER_ID ORDER BY O.ORDER_DATE ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW ) AS RUNNING_TOTAL FROM ORDER_HEADER O WHERE O.ORDER_DATE >= DATE('2024-01-01') ORDER BY O.CUSTOMER_ID, O.ORDER_DATE WITH UR; 
-- ============================================================
-- 08. Set operations
-- ============================================================
SELECT CUSTOMER_ID, EMAIL_ADDRESS FROM CUSTOMER WHERE IS_ACTIVE = 1  UNION  SELECT CUSTOMER_ID, EMAIL_ADDRESS FROM CUSTOMER_ARCHIVE WHERE IS_ACTIVE = 1  EXCEPT  SELECT CUSTOMER_ID, EMAIL_ADDRESS FROM CUSTOMER_SUPPRESSION WHERE IS_ACTIVE = 1  ORDER BY CUSTOMER_ID WITH UR; 
-- ============================================================
-- 09. INSERT statements
-- ============================================================
INSERT INTO CUSTOMER_AUDIT ( CUSTOMER_ID, AUDIT_ACTION, AUDIT_TS, AUDIT_USER ) VALUES ( 1001, 'CREATED', CURRENT TIMESTAMP, CURRENT USER );  INSERT INTO CUSTOMER_AUDIT ( CUSTOMER_ID, AUDIT_ACTION, AUDIT_TS, AUDIT_USER ) SELECT C.CUSTOMER_ID, 'BULK_IMPORT', CURRENT TIMESTAMP, CURRENT USER FROM CUSTOMER C WHERE C.CREATED_AT >= CURRENT DATE - 1 DAY; 
-- ============================================================
-- 10. UPDATE statements
-- ============================================================
UPDATE CUSTOMER SET EMAIL_ADDRESS = LOWER(EMAIL_ADDRESS), UPDATED_AT = CURRENT TIMESTAMP, UPDATED_BY = CURRENT USER WHERE EMAIL_ADDRESS IS NOT NULL AND IS_ACTIVE = 1;  UPDATE ORDER_HEADER O SET STATUS_CODE = 'CLOSED', UPDATED_AT = CURRENT TIMESTAMP WHERE O.STATUS_CODE = 'SHIPPED' AND EXISTS ( SELECT 1 FROM ORDER_DELIVERY D WHERE D.ORDER_ID = O.ORDER_ID AND D.DELIVERED_AT IS NOT NULL ); 
-- ============================================================
-- 11. DELETE statements
-- ============================================================
DELETE FROM SESSION_TEMP_CUSTOMER WHERE CREATED_AT < CURRENT TIMESTAMP - 1 DAY;  DELETE FROM CUSTOMER_STAGE S WHERE EXISTS ( SELECT 1 FROM CUSTOMER C WHERE C.EXTERNAL_CUSTOMER_ID = S.EXTERNAL_CUSTOMER_ID ); 
-- ============================================================
-- 12. MERGE statement
-- ============================================================
MERGE INTO TGT_CUSTOMER_SUMMARY T USING ( SELECT C.CUSTOMER_ID, C.CUSTOMER_NAME, COUNT(O.ORDER_ID) AS ORDER_COUNT, SUM(O.TOTAL_AMOUNT) AS TOTAL_AMOUNT, MAX(O.ORDER_DATE) AS LAST_ORDER_DATE FROM CUSTOMER C LEFT JOIN ORDER_HEADER O ON O.CUSTOMER_ID = C.CUSTOMER_ID AND O.STATUS_CODE IN ('PAID', 'SHIPPED', 'CLOSED') GROUP BY C.CUSTOMER_ID, C.CUSTOMER_NAME ) S ON T.CUSTOMER_ID = S.CUSTOMER_ID WHEN MATCHED THEN UPDATE SET T.CUSTOMER_NAME = S.CUSTOMER_NAME, T.ORDER_COUNT = S.ORDER_COUNT, T.TOTAL_AMOUNT = S.TOTAL_AMOUNT, T.LAST_ORDER_DATE = S.LAST_ORDER_DATE, T.UPDATED_AT = CURRENT TIMESTAMP WHEN NOT MATCHED THEN INSERT ( CUSTOMER_ID, CUSTOMER_NAME, ORDER_COUNT, TOTAL_AMOUNT, LAST_ORDER_DATE, CREATED_AT ) VALUES ( S.CUSTOMER_ID, S.CUSTOMER_NAME, S.ORDER_COUNT, S.TOTAL_AMOUNT, S.LAST_ORDER_DATE, CURRENT TIMESTAMP ); 
-- ============================================================
-- 13. DDL: schema, table, indexes
-- ============================================================
CREATE SCHEMA REPORTING;  CREATE TABLE REPORTING.CUSTOMER_SUMMARY ( CUSTOMER_ID INTEGER NOT NULL, CUSTOMER_NAME VARCHAR(200) NOT NULL, ORDER_COUNT INTEGER NOT NULL DEFAULT 0, TOTAL_AMOUNT DECIMAL(15, 2) NOT NULL DEFAULT 0, LAST_ORDER_DATE DATE, CUSTOMER_SEGMENT VARCHAR(20), CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP, UPDATED_AT TIMESTAMP, CONSTRAINT PK_CUSTOMER_SUMMARY PRIMARY KEY (CUSTOMER_ID) );  CREATE INDEX REPORTING.IX_CUSTOMER_SUMMARY_SEGMENT ON REPORTING.CUSTOMER_SUMMARY ( CUSTOMER_SEGMENT, TOTAL_AMOUNT DESC );  CREATE VIEW REPORTING.V_ACTIVE_CUSTOMER_SUMMARY AS SELECT C.CUSTOMER_ID, C.CUSTOMER_NAME, S.ORDER_COUNT, S.TOTAL_AMOUNT, S.CUSTOMER_SEGMENT FROM CUSTOMER C INNER JOIN REPORTING.CUSTOMER_SUMMARY S ON S.CUSTOMER_ID = C.CUSTOMER_ID WHERE C.IS_ACTIVE = 1; 
-- ============================================================
-- 14. ALTER statements
-- ============================================================
ALTER TABLE REPORTING.CUSTOMER_SUMMARY ADD COLUMN LAST_RECALCULATED_AT TIMESTAMP;  ALTER TABLE REPORTING.CUSTOMER_SUMMARY ALTER COLUMN CUSTOMER_SEGMENT SET DATA TYPE VARCHAR(30);  ALTER TABLE REPORTING.CUSTOMER_SUMMARY ADD CONSTRAINT CK_CUSTOMER_SUMMARY_TOTAL CHECK (TOTAL_AMOUNT >= 0); 
-- ============================================================
-- 15. DB2 temporary table
-- ============================================================
DECLARE GLOBAL TEMPORARY TABLE SESSION.CUSTOMER_WORK ( CUSTOMER_ID INTEGER NOT NULL, CUSTOMER_NAME VARCHAR(200), TOTAL_AMOUNT DECIMAL(15, 2) ) ON COMMIT PRESERVE ROWS NOT LOGGED;  INSERT INTO SESSION.CUSTOMER_WORK ( CUSTOMER_ID, CUSTOMER_NAME, TOTAL_AMOUNT ) SELECT C.CUSTOMER_ID, C.CUSTOMER_NAME, COALESCE(SUM(O.TOTAL_AMOUNT), 0) FROM CUSTOMER C LEFT JOIN ORDER_HEADER O ON O.CUSTOMER_ID = C.CUSTOMER_ID GROUP BY C.CUSTOMER_ID, C.CUSTOMER_NAME; 
-- ============================================================
-- 16. Advanced expressions
-- ============================================================
SELECT C.CUSTOMER_ID, VARCHAR_FORMAT(C.CREATED_AT, 'YYYY-MM-DD') AS CREATED_DATE_TEXT, DECIMAL(COALESCE(S.TOTAL_AMOUNT, 0), 15, 2) AS TOTAL_AMOUNT, CASE WHEN NULLIF(TRIM(C.EMAIL_ADDRESS), '') IS NULL THEN 'MISSING' WHEN LOCATE('@', C.EMAIL_ADDRESS) > 1 THEN 'VALIDISH' ELSE 'CHECK' END AS EMAIL_STATUS FROM CUSTOMER C LEFT JOIN REPORTING.CUSTOMER_SUMMARY S ON S.CUSTOMER_ID = C.CUSTOMER_ID WHERE UPPER(C.COUNTRY_CODE) IN ('GR', 'US', 'GB') WITH UR; 
-- ============================================================
-- 17. Procedure with variables, cursor, handler, loop
-- ============================================================
CREATE OR REPLACE PROCEDURE REPORTING.REFRESH_CUSTOMER_SUMMARY ( IN P_BATCH_ID INTEGER, OUT P_ROWS_UPDATED INTEGER ) LANGUAGE SQL BEGIN DECLARE V_CUSTOMER_ID INTEGER; DECLARE V_TOTAL_AMOUNT DECIMAL(15, 2); DECLARE V_DONE SMALLINT DEFAULT 0;  DECLARE C_CUSTOMERS CURSOR FOR SELECT CUSTOMER_ID, SUM(TOTAL_AMOUNT) AS TOTAL_AMOUNT FROM ORDER_HEADER WHERE BATCH_ID = P_BATCH_ID AND STATUS_CODE IN ('PAID', 'SHIPPED', 'CLOSED') GROUP BY CUSTOMER_ID;  DECLARE CONTINUE HANDLER FOR NOT FOUND SET V_DONE = 1;  SET P_ROWS_UPDATED = 0;  OPEN C_CUSTOMERS;  CUSTOMER_LOOP: LOOP FETCH C_CUSTOMERS INTO V_CUSTOMER_ID, V_TOTAL_AMOUNT;  IF V_DONE = 1 THEN LEAVE CUSTOMER_LOOP; END IF;  MERGE INTO REPORTING.CUSTOMER_SUMMARY T USING ( SELECT V_CUSTOMER_ID AS CUSTOMER_ID, V_TOTAL_AMOUNT AS TOTAL_AMOUNT FROM SYSIBM.SYSDUMMY1 ) S ON T.CUSTOMER_ID = S.CUSTOMER_ID WHEN MATCHED THEN UPDATE SET T.TOTAL_AMOUNT = S.TOTAL_AMOUNT, T.UPDATED_AT = CURRENT TIMESTAMP WHEN NOT MATCHED THEN INSERT ( CUSTOMER_ID, CUSTOMER_NAME, ORDER_COUNT, TOTAL_AMOUNT, CREATED_AT ) VALUES ( S.CUSTOMER_ID, 'UNKNOWN', 0, S.TOTAL_AMOUNT, CURRENT TIMESTAMP );  SET P_ROWS_UPDATED = P_ROWS_UPDATED + 1; END LOOP;  CLOSE C_CUSTOMERS; END; 
-- ============================================================
-- 18. Scalar function
-- ============================================================
CREATE OR REPLACE FUNCTION REPORTING.CUSTOMER_SEGMENT ( P_TOTAL_AMOUNT DECIMAL(15, 2) ) RETURNS VARCHAR(30) LANGUAGE SQL DETERMINISTIC NO EXTERNAL ACTION BEGIN ATOMIC RETURN CASE WHEN P_TOTAL_AMOUNT >= 10000 THEN 'VIP' WHEN P_TOTAL_AMOUNT >= 5000 THEN 'GOLD' WHEN P_TOTAL_AMOUNT >= 1000 THEN 'SILVER' ELSE 'STANDARD' END; END; 
-- ============================================================
-- 19. Dynamic SQL inside procedure
-- ============================================================
CREATE OR REPLACE PROCEDURE REPORTING.RUN_DYNAMIC_CUSTOMER_COUNT ( IN P_SCHEMA_NAME VARCHAR(128), OUT P_CUSTOMER_COUNT INTEGER ) LANGUAGE SQL BEGIN DECLARE V_SQL VARCHAR(4000);  SET V_SQL = 'SELECT COUNT(*) FROM ' || P_SCHEMA_NAME || '.CUSTOMER WHERE IS_ACTIVE = 1';  PREPARE S1 FROM V_SQL; EXECUTE S1 INTO P_CUSTOMER_COUNT; END; 
-- ============================================================
-- 20. Error handling and SIGNAL
-- ============================================================
CREATE OR REPLACE PROCEDURE REPORTING.VALIDATE_CUSTOMER ( IN P_CUSTOMER_ID INTEGER ) LANGUAGE SQL BEGIN IF P_CUSTOMER_ID IS NULL THEN SIGNAL SQLSTATE '75001' SET MESSAGE_TEXT = 'Customer id is required'; END IF;  IF NOT EXISTS ( SELECT 1 FROM CUSTOMER WHERE CUSTOMER_ID = P_CUSTOMER_ID ) THEN SIGNAL SQLSTATE '75002' SET MESSAGE_TEXT = 'Customer does not exist'; END IF; END; 
-- ============================================================
-- 21. Locking / optimization clauses
-- ============================================================
SELECT C.CUSTOMER_ID, C.CUSTOMER_NAME, O.ORDER_ID, O.TOTAL_AMOUNT FROM CUSTOMER C INNER JOIN ORDER_HEADER O ON O.CUSTOMER_ID = C.CUSTOMER_ID WHERE C.IS_ACTIVE = 1 AND O.STATUS_CODE = 'PAID' OPTIMIZE FOR 100 ROWS WITH UR;  SELECT CUSTOMER_ID, CUSTOMER_NAME FROM CUSTOMER WHERE CUSTOMER_ID = 1001 FOR UPDATE OF CUSTOMER_NAME, EMAIL_ADDRESS WITH RS; 
-- ============================================================
-- 22. Comments and string edge cases
-- ============================================================
SELECT 'SELECT * FROM FAKE_TABLE WHERE VALUE = ''NOT SQL''' AS SQL_TEXT, '-- this is not a real comment inside a string' AS COMMENT_TEXT, '/* this is also not a real block comment inside a string */' AS BLOCK_COMMENT_TEXT FROM SYSIBM.SYSDUMMY1;
SELECT CUSTOMER_ID, -- inline comment beside select list item
CUSTOMER_NAME, EMAIL_ADDRESS FROM CUSTOMER WHERE IS_ACTIVE = 1
-- inline comment beside predicate
AND CUSTOMER_NAME LIKE 'A%' WITH UR; 
/* Block comment with SQL-looking text: SELECT * FROM SHOULD_NOT_FORMAT_THIS; */
SELECT COUNT(*) AS CUSTOMER_COUNT FROM CUSTOMER WITH UR;

-- ============================================================
-- 23. Personal Query for Comment handling
-- ============================================================
SELECT A.ID,
       SUM(CASE
             WHEN A.TYPE IN (-- comment one
                             'PAYMENT',
                             -- comment two
                             'EXPORT',
                             'LEAKAGE') THEN A.AMOUNT
             ELSE 0
           END) AS TOTAL_AMOUNT,
       CASE
         WHEN A.FLAG = 'Y' THEN 1 -- inline flag comment
         ELSE 0
       END AS IS_ACTIVE
  FROM ACCOUNT A
 WHERE A.STATUS = 'OPEN'
   AND A.TYPE <> 'TEST'
    OR A.TYPE IS NULL
 GROUP BY A.ID,
          CASE
            WHEN A.FLAG = 'Y' THEN 1
            ELSE 0
          END
  WITH UR;