/*
 * CLEANED INPUT
 * Fixed broken token boundaries from the uploaded BEFORE script.
 */

-- ============================================================
-- 01. Extremely complicated SELECT statement
-- ============================================================
WITH CUSTOMER_BASE AS (SELECT C.CUSTOMER_ID, C.CUSTOMER_NAME, C.COUNTRY_CODE, C.CREATED_AT, C.IS_ACTIVE, COALESCE(NULLIF(TRIM(C.EMAIL_ADDRESS), ''), 'NO_EMAIL') AS EMAIL_ADDRESS, CASE WHEN C.IS_ACTIVE = 1 AND C.CREATED_AT >= DATE('2024-01-01') THEN 'NEW_ACTIVE' WHEN C.IS_ACTIVE = 1 THEN 'ACTIVE' ELSE 'INACTIVE' END AS CUSTOMER_STATUS FROM CUSTOMER C WHERE C.COUNTRY_CODE IN ('GR', 'US', 'GB', 'DE') AND EXISTS (SELECT 1 FROM ORDER_HEADER OH WHERE OH.CUSTOMER_ID = C.CUSTOMER_ID AND OH.STATUS_CODE IN ('PAID', 'SHIPPED', 'CLOSED'))),
ORDER_ENRICH AS (SELECT O.CUSTOMER_ID, O.ORDER_ID, O.ORDER_DATE, O.STATUS_CODE, O.TOTAL_AMOUNT, O.CURRENCY_CODE, ROW_NUMBER() OVER (PARTITION BY O.CUSTOMER_ID ORDER BY O.ORDER_DATE DESC, O.ORDER_ID DESC) AS LAST_ORDER_RN, SUM(O.TOTAL_AMOUNT) OVER (PARTITION BY O.CUSTOMER_ID ORDER BY O.ORDER_DATE ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS RUNNING_TOTAL, CASE WHEN O.TOTAL_AMOUNT >= 10000 THEN 'VERY_HIGH' WHEN O.TOTAL_AMOUNT >= 5000 THEN 'HIGH' WHEN O.TOTAL_AMOUNT >= 1000 THEN 'MEDIUM' ELSE 'LOW' END AS ORDER_VALUE_BAND FROM ORDER_HEADER O WHERE O.ORDER_DATE BETWEEN DATE('2024-01-01') AND DATE('2024-12-31') AND O.STATUS_CODE IN ('PAID', 'SHIPPED', 'CLOSED')),
CUSTOMER_TOTALS AS (SELECT OE.CUSTOMER_ID, COUNT(*) AS ORDER_COUNT, SUM(OE.TOTAL_AMOUNT) AS TOTAL_AMOUNT, AVG(OE.TOTAL_AMOUNT) AS AVG_AMOUNT, MAX(OE.ORDER_DATE) AS LAST_ORDER_DATE, SUM(CASE WHEN OE.ORDER_VALUE_BAND IN ('VERY_HIGH', 'HIGH') THEN 1 ELSE 0 END) AS HIGH_VALUE_ORDER_COUNT FROM ORDER_ENRICH OE GROUP BY OE.CUSTOMER_ID HAVING SUM(OE.TOTAL_AMOUNT) >= 1000)
SELECT CB.CUSTOMER_ID, CB.CUSTOMER_NAME, CB.EMAIL_ADDRESS, CB.COUNTRY_CODE, CB.CUSTOMER_STATUS, CT.ORDER_COUNT, CT.TOTAL_AMOUNT, CT.AVG_AMOUNT, CT.LAST_ORDER_DATE, CT.HIGH_VALUE_ORDER_COUNT, LO.ORDER_ID AS LAST_ORDER_ID, LO.STATUS_CODE AS LAST_ORDER_STATUS, CASE WHEN CT.TOTAL_AMOUNT >= 25000 AND CT.HIGH_VALUE_ORDER_COUNT >= 3 THEN 'PLATINUM' WHEN CT.TOTAL_AMOUNT >= 10000 THEN 'VIP' WHEN CT.TOTAL_AMOUNT >= 5000 THEN 'GOLD' WHEN CT.TOTAL_AMOUNT >= 1000 THEN 'SILVER' ELSE 'STANDARD' END AS CUSTOMER_SEGMENT, (SELECT COUNT(*) FROM CUSTOMER_NOTE CN WHERE CN.CUSTOMER_ID = CB.CUSTOMER_ID AND CN.IS_ACTIVE = 1) AS ACTIVE_NOTE_COUNT
FROM CUSTOMER_BASE CB
INNER JOIN CUSTOMER_TOTALS CT ON CT.CUSTOMER_ID = CB.CUSTOMER_ID
LEFT JOIN ORDER_ENRICH LO ON LO.CUSTOMER_ID = CB.CUSTOMER_ID AND LO.LAST_ORDER_RN = 1
LEFT JOIN CUSTOMER_ADDRESS CA ON CA.CUSTOMER_ID = CB.CUSTOMER_ID AND CA.IS_PRIMARY = 1 AND CA.VALID_FROM <= CURRENT DATE AND (CA.VALID_TO IS NULL OR CA.VALID_TO >= CURRENT DATE)
WHERE CB.IS_ACTIVE = 1 AND NOT EXISTS (SELECT 1 FROM CUSTOMER_BLACKLIST BL WHERE BL.CUSTOMER_ID = CB.CUSTOMER_ID AND BL.IS_ACTIVE = 1) AND (CT.TOTAL_AMOUNT >= 5000 OR CB.COUNTRY_CODE = 'GR')
GROUP BY CB.CUSTOMER_ID, CB.CUSTOMER_NAME, CB.EMAIL_ADDRESS, CB.COUNTRY_CODE, CB.CUSTOMER_STATUS, CT.ORDER_COUNT, CT.TOTAL_AMOUNT, CT.AVG_AMOUNT, CT.LAST_ORDER_DATE, CT.HIGH_VALUE_ORDER_COUNT, LO.ORDER_ID, LO.STATUS_CODE
ORDER BY CT.TOTAL_AMOUNT DESC, CB.CUSTOMER_NAME ASC, CB.CUSTOMER_ID ASC
FETCH FIRST 500 ROWS ONLY
WITH UR;

-- ============================================================
-- 02. Extremely complicated MERGE statement
-- ============================================================
MERGE INTO REPORTING.CUSTOMER_SUMMARY T
USING (WITH BASE_ORDERS AS (SELECT O.CUSTOMER_ID, O.ORDER_ID, O.ORDER_DATE, O.STATUS_CODE, O.TOTAL_AMOUNT, O.CURRENCY_CODE, ROW_NUMBER() OVER (PARTITION BY O.CUSTOMER_ID ORDER BY O.ORDER_DATE DESC, O.ORDER_ID DESC) AS RN FROM ORDER_HEADER O WHERE O.BATCH_ID = 20260520 AND O.STATUS_CODE IN ('PAID', 'SHIPPED', 'CLOSED')), CUSTOMER_AGG AS (SELECT BO.CUSTOMER_ID, COUNT(*) AS ORDER_COUNT, SUM(BO.TOTAL_AMOUNT) AS TOTAL_AMOUNT, AVG(BO.TOTAL_AMOUNT) AS AVG_AMOUNT, MAX(BO.ORDER_DATE) AS LAST_ORDER_DATE, SUM(CASE WHEN BO.TOTAL_AMOUNT >= 5000 THEN 1 ELSE 0 END) AS HIGH_VALUE_ORDER_COUNT FROM BASE_ORDERS BO GROUP BY BO.CUSTOMER_ID) SELECT C.CUSTOMER_ID, C.CUSTOMER_NAME, C.COUNTRY_CODE, CA.ORDER_COUNT, CA.TOTAL_AMOUNT, CA.AVG_AMOUNT, CA.LAST_ORDER_DATE, CA.HIGH_VALUE_ORDER_COUNT, CASE WHEN CA.TOTAL_AMOUNT >= 25000 THEN 'PLATINUM' WHEN CA.TOTAL_AMOUNT >= 10000 THEN 'VIP' WHEN CA.TOTAL_AMOUNT >= 5000 THEN 'GOLD' WHEN CA.TOTAL_AMOUNT >= 1000 THEN 'SILVER' ELSE 'STANDARD' END AS CUSTOMER_SEGMENT FROM CUSTOMER C INNER JOIN CUSTOMER_AGG CA ON CA.CUSTOMER_ID = C.CUSTOMER_ID LEFT JOIN BASE_ORDERS BO ON BO.CUSTOMER_ID = C.CUSTOMER_ID AND BO.RN = 1 WHERE C.IS_ACTIVE = 1 AND NOT EXISTS (SELECT 1 FROM CUSTOMER_BLACKLIST BL WHERE BL.CUSTOMER_ID = C.CUSTOMER_ID AND BL.IS_ACTIVE = 1)) S
ON T.CUSTOMER_ID = S.CUSTOMER_ID
WHEN MATCHED THEN UPDATE SET T.CUSTOMER_NAME = S.CUSTOMER_NAME, T.COUNTRY_CODE = S.COUNTRY_CODE, T.ORDER_COUNT = S.ORDER_COUNT, T.TOTAL_AMOUNT = S.TOTAL_AMOUNT, T.AVG_AMOUNT = S.AVG_AMOUNT, T.LAST_ORDER_DATE = S.LAST_ORDER_DATE, T.HIGH_VALUE_ORDER_COUNT = S.HIGH_VALUE_ORDER_COUNT, T.CUSTOMER_SEGMENT = S.CUSTOMER_SEGMENT, T.UPDATED_AT = CURRENT TIMESTAMP, T.UPDATED_BY = CURRENT USER
WHEN NOT MATCHED THEN INSERT (CUSTOMER_ID, CUSTOMER_NAME, COUNTRY_CODE, ORDER_COUNT, TOTAL_AMOUNT, AVG_AMOUNT, LAST_ORDER_DATE, HIGH_VALUE_ORDER_COUNT, CUSTOMER_SEGMENT, CREATED_AT, CREATED_BY) VALUES (S.CUSTOMER_ID, S.CUSTOMER_NAME, S.COUNTRY_CODE, S.ORDER_COUNT, S.TOTAL_AMOUNT, S.AVG_AMOUNT, S.LAST_ORDER_DATE, S.HIGH_VALUE_ORDER_COUNT, S.CUSTOMER_SEGMENT, CURRENT TIMESTAMP, CURRENT USER);

-- ============================================================
-- 03. Extremely complicated UPDATE statement
-- ============================================================
UPDATE REPORTING.CUSTOMER_SUMMARY T
SET CUSTOMER_SEGMENT = CASE WHEN T.TOTAL_AMOUNT >= 25000 AND T.HIGH_VALUE_ORDER_COUNT >= 3 THEN 'PLATINUM' WHEN T.TOTAL_AMOUNT >= 10000 THEN 'VIP' WHEN T.TOTAL_AMOUNT >= 5000 THEN 'GOLD' WHEN T.TOTAL_AMOUNT >= 1000 THEN 'SILVER' ELSE 'STANDARD' END, UPDATED_AT = CURRENT TIMESTAMP, UPDATED_BY = CURRENT USER, REVIEW_REQUIRED_FLG = CASE WHEN EXISTS (SELECT 1 FROM CUSTOMER_BLACKLIST BL WHERE BL.CUSTOMER_ID = T.CUSTOMER_ID AND BL.IS_ACTIVE = 1) THEN 1 WHEN T.TOTAL_AMOUNT >= 50000 AND T.ORDER_COUNT <= 2 THEN 1 ELSE 0 END
WHERE T.CUSTOMER_ID IN (SELECT C.CUSTOMER_ID FROM CUSTOMER C INNER JOIN ORDER_HEADER O ON O.CUSTOMER_ID = C.CUSTOMER_ID AND O.STATUS_CODE IN ('PAID', 'SHIPPED', 'CLOSED') LEFT JOIN CUSTOMER_ADDRESS A ON A.CUSTOMER_ID = C.CUSTOMER_ID AND A.IS_PRIMARY = 1 WHERE C.IS_ACTIVE = 1 AND O.ORDER_DATE >= DATE('2024-01-01') GROUP BY C.CUSTOMER_ID HAVING SUM(O.TOTAL_AMOUNT) >= 1000) AND NOT EXISTS (SELECT 1 FROM CUSTOMER_SUPPRESSION S WHERE S.CUSTOMER_ID = T.CUSTOMER_ID AND S.SUPPRESSION_TYPE IN ('LEGAL', 'GDPR') AND S.IS_ACTIVE = 1);

-- ============================================================
-- 04. Extremely complicated DELETE statement
-- ============================================================
DELETE FROM CUSTOMER_STAGE S
WHERE S.LOAD_BATCH_ID = 20260520
AND (S.EXTERNAL_CUSTOMER_ID IS NULL OR TRIM(S.EXTERNAL_CUSTOMER_ID) = '' OR S.EMAIL_ADDRESS IS NULL OR LOCATE('@', S.EMAIL_ADDRESS) = 0)
AND NOT EXISTS (SELECT 1 FROM CUSTOMER C WHERE C.EXTERNAL_CUSTOMER_ID = S.EXTERNAL_CUSTOMER_ID AND C.IS_ACTIVE = 1)
AND EXISTS (SELECT 1 FROM LOAD_AUDIT A INNER JOIN LOAD_CONTROL LC ON LC.LOAD_BATCH_ID = A.LOAD_BATCH_ID AND LC.SOURCE_SYSTEM = A.SOURCE_SYSTEM LEFT JOIN LOAD_ERROR E ON E.LOAD_BATCH_ID = A.LOAD_BATCH_ID AND E.ERROR_SEVERITY = 'FATAL' WHERE A.LOAD_BATCH_ID = S.LOAD_BATCH_ID AND A.SOURCE_SYSTEM = S.SOURCE_SYSTEM AND A.LOAD_STATUS IN ('VALIDATED', 'PARTIAL') AND E.LOAD_BATCH_ID IS NULL)
AND S.CREATED_AT < CURRENT TIMESTAMP - 2 HOURS;
