SELECT *
  FROM CUSTOMER
LIMIT 100
  WITH UR;

SELECT CUSTOMER_ID,
       CUSTOMER_NAME,
       EMAIL_ADDRESS
  FROM CUSTOMER
 WHERE CUSTOMER_ID = 1
LIMIT 100
  WITH UR;

INSERT INTO CUSTOMER_AUDIT (
    CUSTOMER_ID,
    ACTION_CODE,
    CREATED_AT
)
VALUES (
    1,
    'CREATE',
    CURRENT TIMESTAMP
);

UPDATE CUSTOMER
   SET EMAIL_ADDRESS = 'A@B.COM',
       UPDATED_AT = CURRENT TIMESTAMP
 WHERE CUSTOMER_ID = 1 WITH NC;

DELETE FROM CUSTOMER_SESSION
 WHERE CUSTOMER_ID = 1 WITH NC;

 MERGE INTO CUSTOMER_TARGET T
 USING ( SELECT CUSTOMER_ID,
              EMAIL_ADDRESS
         FROM CUSTOMER_SOURCE
        WHERE BATCH_ID = 1
       ) S
    ON (T.CUSTOMER_ID = S.CUSTOMER_ID) WHEN MATCHED AND (T.EMAIL_ADDRESS <> S.EMAIL_ADDRESS) THEN UPDATE SET T.EMAIL_ADDRESS = S.EMAIL_ADDRESS, T.UPDATED_AT = CURRENT TIMESTAMP
  WHEN NOT MATCHED THEN INSERT (CUSTOMER_ID, EMAIL_ADDRESS, CREATED_AT) VALUES (S.CUSTOMER_ID, S.EMAIL_ADDRESS, CURRENT TIMESTAMP) WITH NC;
