SELECT CUSTOMER_ID,
       CUSTOMER_NAME
  FROM CUSTOMER
 WHERE IS_ACTIVE = 1
UNION
SELECT CUSTOMER_ID,
       CUSTOMER_NAME
  FROM CUSTOMER_ARCHIVE
 WHERE IS_ACTIVE = 1
 ORDER BY CUSTOMER_ID ASC
 FETCH FIRST 100 ROWS ONLY
  WITH UR;

SELECT CUSTOMER_ID,
       EMAIL_ADDRESS
  FROM CUSTOMER
 WHERE IS_ACTIVE = 1
UNION ALL
SELECT CUSTOMER_ID,
       EMAIL_ADDRESS
  FROM CUSTOMER_STAGE
 WHERE BATCH_ID = 20260520
EXCEPT
SELECT CUSTOMER_ID,
       EMAIL_ADDRESS
  FROM CUSTOMER_BLACKLIST
 WHERE IS_ACTIVE = 1
 ORDER BY CUSTOMER_ID ASC, EMAIL_ADDRESS ASC
 FETCH FIRST 250 ROWS ONLY
  WITH UR;

WITH ACTIVE_CUSTOMERS AS ( SELECT CUSTOMER_ID,
                                  CUSTOMER_NAME,
                                  EMAIL_ADDRESS
                             FROM CUSTOMER
                            WHERE IS_ACTIVE = 1 ),
     STAGED_CUSTOMERS AS ( SELECT CUSTOMER_ID,
                                  CUSTOMER_NAME,
                                  EMAIL_ADDRESS
                             FROM CUSTOMER_STAGE
                            WHERE BATCH_ID = 20260520 )
SELECT CUSTOMER_ID,
       CUSTOMER_NAME,
       EMAIL_ADDRESS
  FROM ACTIVE_CUSTOMERS
UNION ALL
SELECT CUSTOMER_ID,
       CUSTOMER_NAME,
       EMAIL_ADDRESS
  FROM STAGED_CUSTOMERS
EXCEPT
SELECT CUSTOMER_ID,
       CUSTOMER_NAME,
       EMAIL_ADDRESS
  FROM CUSTOMER_BLACKLIST
 WHERE IS_ACTIVE = 1
 ORDER BY CUSTOMER_ID ASC
 FETCH FIRST 500 ROWS ONLY
  WITH UR;
