INSERT INTO SESSION.REC_SOURCE_DATA
SELECT "YEAR",
       "MONTH",
       CST_CID,
       'CST',
       'INT_REV',
       'MON',
       COALESCE (INT_REV_MON, 0)
  FROM DW_CORPT.PRC_CST_M_MSR
 WHERE ("YEAR", "MONTH") IN (SELECT "YEAR", "MONTH" FROM SESSION.REC_PERIODS);
